### ISSUE TITLE
pdftozpl error with status code 101

### ISSUE THREAD

**Issue by isadon** [kylemacfarlane/zplgrf#1]
I am trying to integrate zplgrf on OS X High Sierra 10.13.4 (17E199) to print to my Zebra ZP450 and I am somewhat successful but CUPS is giving me an error and not printing anything. How can I properly debug so that I can see what the true issue is. 

```
D [04/Apr/2018:01:27:55 -0400] [Job 286] execv failed: Operation not permitted
1836 D [04/Apr/2018:01:27:55 -0400] [Job 286] PID 3835 (/usr/libexec/cups/filter/pdftozpl) stopped with status 101 (Operation not permitted)
```

Definitely seems like a permissions error but my pdftozpl script is owned by root though I am not sure what user CUPS tries to execute the script as.

**Comment by kylemacfarlane** [comment]
Sorry but I can't help with CUPS configuration.

Since cups-filters added the center of pixel option in 1.11.4 there is no need to use the pdftozpl filter.
